version: "3.9"

services:
  app:
    build: .
    container_name: blogg_app
    ports:
      - "3001:3001"
    environment:
      DB_HOST: yamabiko.proxy.rlwy.net
      DB_USER: root
      DB_PASSWORD: vnLUvyFUQAvLaeUylfyTbeLZvaWoRMCX
      DB_NAME: railway
      DB_PORT: 54981
      SECRET_KEY: cr7-Goat